package com.egdcoding.dailydoseofmotivation

import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase

fun addQuotesToFirebase(quotes: List<String>) {
    val db = Firebase.firestore
    val batch = db.batch()
    val collectionRef = db.collection("quotes")

    quotes.forEach { quoteText ->
        val documentRef = collectionRef.document() // Create a new document for each quote
        val quote = hashMapOf("quote" to quoteText)
        batch.set(documentRef, quote)
    }

    batch.commit()
        .addOnSuccessListener {
            println("All quotes successfully added.")
        }
        .addOnFailureListener { e ->
            println("Error adding quotes: ${e.message}")
        }
}

fun addQuoteList()
{

    /*
    val quotesList = listOf(
        "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
        "The only way to do great work is to love what you do. - Steve Jobs",
        "Happiness depends upon ourselves. - Aristotle",
        "Do what you can, with what you have, where you are. - Theodore Roosevelt",
        "It is not length of life, but depth of life. - Ralph Waldo Emerson",
        "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Will Durant (on Aristotle)",
        "Act as if what you do makes a difference. It does. - William James",
        "Knowing yourself is the beginning of all wisdom. - Aristotle",
        "Courage is not simply one of the virtues, but the form of every virtue at the testing point. - C.S. Lewis",
        "Dwell on the beauty of life. Watch the stars, and see yourself running with them. - Marcus Aurelius",
        "A journey of a thousand miles begins with a single step. - Lao Tzu",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
        "Life is really simple, but we insist on making it complicated. - Confucius",
        "To live is to suffer, to survive is to find some meaning in the suffering. - Friedrich Nietzsche",
        "An unexamined life is not worth living. - Socrates",
        "The best way to predict the future is to create it. - Peter Drucker",
        "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
        "He who opens a school door, closes a prison. - Victor Hugo",
        "We do not see things as they are, we see them as we are. - Anaïs Nin",
        "Well begun is half done. - Aristotle",
        "All that we are is the result of what we have thought. - Buddha",
        "Difficulties strengthen the mind, as labor does the body. - Seneca",
        "To improve is to change; to be perfect is to change often. - Winston Churchill",
        "The mind is everything. What you think you become. - Buddha",
        "Opportunities multiply as they are seized. - Sun Tzu",
        "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. - Marcus Aurelius",
        "A fool thinks himself to be wise, but a wise man knows himself to be a fool. - William Shakespeare",
        "You must be the change you wish to see in the world. - Mahatma Gandhi",
        "He who is not courageous enough to take risks will accomplish nothing in life. - Muhammad Ali",
        "Great acts are made up of small deeds. - Lao Tzu",
        "A day without laughter is a day wasted. - Charlie Chaplin",
        "If you cannot do great things, do small things in a great way. - Napoleon Hill",
        "Tough times never last, but tough people do. - Robert H. Schuller",
        "You will face many defeats in life, but never let yourself be defeated. - Maya Angelou",
        "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
        "Injustice anywhere is a threat to justice everywhere. - Martin Luther King Jr.",
        "Life is either a daring adventure or nothing at all. - Helen Keller",
        "Quality means doing it right when no one is looking. - Henry Ford",
        "Success is how high you bounce when you hit bottom. - George S. Patton",
        "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
        "Be yourself; everyone else is already taken. - Oscar Wilde",
        "Dream big and dare to fail. - Norman Vaughan",
        "Energy and persistence conquer all things. - Benjamin Franklin",
        "Nothing great was ever achieved without enthusiasm. - Ralph Waldo Emerson",
        "Do what you feel in your heart to be right—for you'll be criticized anyway. - Eleanor Roosevelt",
        "Life isn't about finding yourself. Life is about creating yourself. - George Bernard Shaw",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "Be not afraid of growing slowly, be afraid only of standing still. - Chinese Proverb",
        "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
        "It always seems impossible until it’s done. - Nelson Mandela",
        "Man is not made for defeat. A man can be destroyed but not defeated. - Ernest Hemingway",
        "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
        "Be like a postage stamp—stick to one thing until you get there. - Josh Billings",
        "When we strive to become better than we are, everything around us becomes better too. - Paulo Coelho",
        "Don’t count the days, make the days count. - Muhammad Ali",
        "If you’re going through hell, keep going. - Winston Churchill",
        "What would life be if we had no courage to attempt anything? - Vincent van Gogh",
        "Effort only fully releases its reward after a person refuses to quit. - Napoleon Hill",
        "It is never too late to be what you might have been. - George Eliot",
        "You cannot teach a man anything; you can only help him find it within himself. - Galileo Galilei",
        "The weak can never forgive. Forgiveness is the attribute of the strong. - Mahatma Gandhi",
        "Adversity causes some men to break; others to break records. - William Arthur Ward",
        "He who learns but does not think is lost. He who thinks but does not learn is in great danger. - Confucius",
        "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
        "A champion is defined not by their wins but by how they can recover when they fall. - Serena Williams",
        "The secret of getting ahead is getting started. - Mark Twain",
        "All things are difficult before they are easy. - Thomas Fuller",
        "The way to get started is to quit talking and begin doing. - Walt Disney",
        "Life is not about waiting for the storm to pass but about learning to dance in the rain. - Vivian Greene",
        "Do what is right, not what is easy nor what is popular. - Roy T. Bennett",
        "Failure is simply the opportunity to begin again, this time more intelligently. - Henry Ford",
        "The more I want to get something done, the less I call it work. - Richard Bach",
        "If opportunity doesn’t knock, build a door. - Milton Berle",
        "You cannot swim for new horizons until you have the courage to lose sight of the shore. - William Faulkner",
        "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
        "Do what you love, and the money will follow. - Marsha Sinetar",
        "Patience, persistence, and perspiration make an unbeatable combination for success. - Napoleon Hill",
        "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
        "Turn your wounds into wisdom. - Oprah Winfrey",
        "Small deeds done are better than great deeds planned. - Peter Marshall",
        "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
        "You can’t use up creativity. The more you use, the more you have. - Maya Angelou",
        "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
        "You may have to fight a battle more than once to win it. - Margaret Thatcher",
        "A person who never made a mistake never tried anything new. - Albert Einstein",
        "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
        "When something is important enough, you do it even if the odds are not in your favor. - Elon Musk",
        "Only those who dare to fail greatly can ever achieve greatly. - Robert F. Kennedy",
        "Be so good they can’t ignore you. - Steve Martin",
        "Strive not to be a success, but rather to be of value. - Albert Einstein",
        "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
        "We become what we think about. - Earl Nightingale",
        "Perfection is not attainable, but if we chase perfection we can catch excellence. - Vince Lombardi",
        "Security is mostly a superstition. Life is either a daring adventure or nothing. - Helen Keller",
        "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. - Dale Carnegie",
        "Whether you think you can or you think you can’t, you’re right. - Henry Ford",
        "You can waste your lives drawing lines. Or you can live your life crossing them. - Shonda Rhimes",
        "One way to keep momentum going is to have constantly greater goals. - Michael Korda",
        "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
        "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
        "Everything you’ve ever wanted is on the other side of fear. - George Addair",
        "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
        "Don’t limit your challenges. Challenge your limits. - Jerry Dunn",
        "A person’s mind is stretched by a new idea or experience and never shrinks back to its former dimensions. - Oliver Wendell Holmes",
        "Opportunities don't happen. You create them. - Chris Grosser",
        "Success is getting what you want. Happiness is wanting what you get. - Dale Carnegie",
        "Dreaming, after all, is a form of planning. - Gloria Steinem",
        "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. - Booker T. Washington",
        "Work hard in silence, let your success be your noise. - Frank Ocean",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
        "Your only limit is your mind. - Unknown",
        "No pressure, no diamonds. - Thomas Carlyle",
        "It does not matter how slowly you go as long as you do not stop. - Confucius",
        "Act without expectation. - Lao Tzu",
        "If you want to shine like the sun, first burn like the sun. - A.P.J. Abdul Kalam",
        "Make each day your masterpiece. - John Wooden",
        "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
        "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
        "A little progress each day adds up to big results. - Satya Nani",
        "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
        "The harder the battle, the sweeter the victory. - Les Brown",
        "A smooth sea never made a skilled sailor. - Franklin D. Roosevelt",
        "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
        "Be the change that you wish to see in the world. - Mahatma Gandhi",
        "I never dreamed about success. I worked for it. - Estée Lauder",
        "Luck is what happens when preparation meets opportunity. - Seneca",
        "Do not wait for leaders; do it alone, person to person. - Mother Teresa",
        "You miss 100% of the shots you don’t take. - Wayne Gretzky",
        "It takes courage to grow up and become who you really are. - E.E. Cummings",
        "Fall seven times, stand up eight. - Japanese Proverb",
        "You are what you do, not what you say you’ll do. - Carl Jung",
        "Hustle until your haters ask if you’re hiring. - Unknown",
        "Don’t wish it were easier. Wish you were better. - Jim Rohn",
        "Success is not just about making money. It's about making a difference. - Unknown",
        "You must expect great things of yourself before you can do them. - Michael Jordan",
        "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
        "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt",
        "Don’t stop when you’re tired. Stop when you’re done. - Unknown",
        "The way to achieve your own success is to be willing to help somebody else get it first. - Iyanla Vanzant",
        "Doubt kills more dreams than failure ever will. - Suzy Kassem",
        "To succeed in life, you need two things: ignorance and confidence. - Mark Twain",
        "The best revenge is massive success. - Frank Sinatra",
        "Failure is an option here. If things are not failing, you are not innovating enough. - Elon Musk",
        "Winners are not people who never fail but people who never quit. - Unknown",
        "One day or day one. You decide. - Unknown",
        "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston Churchill",
        "Chase the vision, not the money; the money will end up following you. - Tony Hsieh",
        "Surround yourself with only people who are going to lift you higher. - Oprah Winfrey",
        "Life shrinks or expands in proportion to one’s courage. - Anaïs Nin",
        "Keep your face always toward the sunshine, and shadows will fall behind you. - Walt Whitman",
        "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
        "Push yourself, because no one else is going to do it for you. - Unknown",
        "Do one thing every day that scares you. - Eleanor Roosevelt",
        "Self-belief and hard work will always earn you success. - Virat Kohli",
        "If you don't value your time, neither will others. - Tim Ferriss",
        "A goal properly set is halfway reached. - Zig Ziglar",
        "Ambition is the path to success. Persistence is the vehicle you arrive in. - Bill Bradley",
        "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
        "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
        "Never let your fear decide your future. - Unknown",
        "Work until your idols become your rivals. - Drake",
        "Your life does not get better by chance, it gets better by change. - Jim Rohn",
        "Someday is not a day of the week. - Denise Brennan-Nelson",
        "Be willing to be a beginner every single morning. - Meister Eckhart",
        "You never fail until you stop trying. - Albert Einstein",
        "Difficult roads often lead to beautiful destinations. - Unknown",
        "The best way out is always through. - Robert Frost",
        "When you know what you want, and want it bad enough, you will find a way to get it. - Jim Rohn",
        "Your dreams don’t work unless you do. - John C. Maxwell",
        "In the middle of every difficulty lies opportunity. - Albert Einstein",
        "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
        "Be stubborn about your goals and flexible about your methods. - Unknown",
        "Don’t wait for opportunity. Create it. - Unknown",
        "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
        "If you want something you've never had, you must be willing to do something you've never done. - Thomas Jefferson",
        "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
        "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
        "Your present circumstances don’t determine where you can go; they merely determine where you start. - Nido Qubein",
        "Great things are done by a series of small things brought together. - Vincent van Gogh",
        "Start by doing what’s necessary; then do what’s possible; and suddenly you are doing the impossible. - Francis of Assisi",
        "Energy and persistence conquer all things. - Benjamin Franklin",
        "You only fail when you stop trying. - Unknown",
        "Life isn’t about finding yourself. Life is about creating yourself. - George Bernard Shaw",
        "Don’t let what you cannot do interfere with what you can do. - John Wooden",
        "Keep going. Everything you need will come to you at the perfect time. - Unknown",
        "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
        "Don’t wait. The time will never be just right. - Napoleon Hill",
        "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. - Jordan Belfort",
        "We may encounter many defeats but we must not be defeated. - Maya Angelou",
        "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller",
        "The best time to plant a tree was 20 years ago. The second-best time is now. - Chinese Proverb",
        "Dare to live the life you have dreamed for yourself. Go forward and make your dreams come true. - Ralph Waldo Emerson",
        "We cannot solve problems with the same thinking we used when we created them. - Albert Einstein",
        "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
        "Difficulties strengthen the mind, as labor does the body. - Seneca",
        "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
    )




    val quotesList = listOf(
        "You have power over your mind—not outside events. Realize this, and you will find strength. - Marcus Aurelius",
        "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
        "It is not death that a man should fear, but he should fear never beginning to live. - Marcus Aurelius",
        "If it is not right, do not do it; if it is not true, do not say it. - Marcus Aurelius",
        "Accept whatever comes to you woven in the pattern of your destiny, for what could more aptly fit your needs? - Marcus Aurelius",
        "The best revenge is not to be like your enemy. - Marcus Aurelius",
        "Look well into yourself; there is a source of strength which will always spring up if you will always look. - Marcus Aurelius",
        "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
        "Because a thing seems difficult for you, do not think it impossible. - Marcus Aurelius",
        "The impediment to action advances action. What stands in the way becomes the way. - Marcus Aurelius",
        "Do every act of your life as though it were the very last act of your life. - Marcus Aurelius",
        "The universe is change; our life is what our thoughts make it. - Marcus Aurelius",
        "The beginning is the most important part of the work. - Plato",
        "Wise men speak because they have something to say; fools because they have to say something. - Plato",
        "Courage is knowing what not to fear. - Plato",
        "An empty vessel makes the loudest sound. - Plato",
        "Ignorance, the root and stem of all evil. - Plato",
        "The measure of a man is what he does with power. - Plato",
        "Opinion is the medium between knowledge and ignorance. - Plato",
        "Music gives a soul to the universe, wings to the mind, flight to the imagination, and life to everything. - Plato",
        "Better a little which is well done, than a great deal imperfectly. - Plato",
        "There is truth in wine and children. - Plato",
        "Excellence is not a gift, but a skill that takes practice. - Plato",
        "A good decision is based on knowledge and not on numbers. - Plato",
        "He who commits injustice is ever made more wretched than he who suffers it. - Plato",
        "Good actions give strength to ourselves and inspire good actions in others. - Plato",
        "The only true wisdom is in knowing you know nothing. - Socrates",
        "He is richest who is content with the least. - Socrates",
        "Strong minds discuss ideas, average minds discuss events, weak minds discuss people. - Socrates",
        "To find yourself, think for yourself. - Socrates",
        "The secret of change is to focus all of your energy, not on fighting the old, but on building the new. - Socrates",
        "Be as you wish to seem. - Socrates",
        "Wisdom begins in wonder. - Socrates",
        "Do not do to others what angers you if done to you by others. - Socrates",
        "The greatest way to live with honor in this world is to be what we pretend to be. - Socrates",
        "Education is the kindling of a flame, not the filling of a vessel. - Socrates",
        "Beware the barrenness of a busy life. - Socrates",
        "He who is not contented with what he has would not be contented with what he wants. - Socrates",
        "Understanding a question is half an answer. - Socrates",
        "Envy is the ulcer of the soul. - Socrates",
        "It's the possibility of having a dream come true that makes life interesting. - Paulo Coelho",
        "Tell your heart that the fear of suffering is worse than the suffering itself. And that no heart has ever suffered when it goes in search of its dreams. - Paulo Coelho",
        "The secret of happiness is to see all the marvels of the world, and never to forget the drops of oil on the spoon. - Paulo Coelho",
        "And, when you want something, all the universe conspires in helping you to achieve it. - Paulo Coelho",
        "The journey is better than the destination.",
        "People learn, at a certain age, that they must go after their dreams no matter what happens. - Paulo Coelho",
        "Remember that wherever your heart is, there you will find your treasure. - Paulo Coelho",
        "The world is changed by your example, not by your opinion. - Paulo Coelho",
        "Every blessing ignored becomes a curse. - Paulo Coelho",
        "When I let go of what I am, I become what I might be. - Lao Tzu",
        "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power. - Lao Tzu",
        "To the mind that is still, the whole universe surrenders. - Lao Tzu",
        "The best fighter is never angry. - Lao Tzu",
        "Those who know do not speak. Those who speak do not know. - Lao Tzu",
        "A good traveler has no fixed plans and is not intent on arriving. - Lao Tzu",
        "He who controls others may be powerful, but he who has mastered himself is mightier still. - Lao Tzu",
        "The more that laws and regulations are given, the more thieves and robbers there will be. - Lao Tzu",
        "Because one believes in oneself, one does not try to convince others. - Lao Tzu"
    )

     */

    val quotesList3 = listOf(
        "Do not pray for an easy life, pray for the strength to endure a difficult one. - Bruce Lee",
        "In the middle of difficulty lies opportunity. - Albert Einstein",
        "Happiness is not by chance, but by choice. - Jim Rohn",
        "The man who moves a mountain begins by carrying away small stones. - Confucius",
        "Act as though it is impossible to fail. - Dorothea Brande",
        "Success is not measured by what you accomplish, but by the opposition you have encountered. - Orison Swett Marden",
        "The greatest wealth is to live content with little. - Plato",
        "Don’t let yesterday take up too much of today. - Will Rogers",
        "Happiness is not something you postpone for the future; it is something you design for the present. - Jim Rohn",
        "The superior man is modest in his speech, but exceeds in his actions. - Confucius",
        "If you want to fly, give up everything that weighs you down. - Buddha",
        "You can’t cross the sea merely by standing and staring at the water. - Rabindranath Tagore",
        "Out of difficulties grow miracles. - Jean de La Bruyère",
        "Everything you can imagine is real. - Pablo Picasso",
        "Silence is a source of great strength. - Lao Tzu",
        "Happiness only real when shared. - Christopher McCandless",
        "Do what you can, with what you’ve got, where you are. - Teddy Roosevelt",
        "A wise man will make more opportunities than he finds. - Francis Bacon",
        "Life is short, and truth works far and lives long: let us then speak the truth. - Arthur Schopenhauer",
        "Dreams don’t work unless you do. - John C. Maxwell",
        "A room without books is like a body without a soul. - Cicero",
        "No man has a good enough memory to be a successful liar. - Abraham Lincoln",
        "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
        "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
        "The best way to cheer yourself is to try to cheer someone else up. - Mark Twain",
        "What we achieve inwardly will change outer reality. - Plutarch",
        "It always seems impossible until it’s done. - Nelson Mandela",
        "Everything has beauty, but not everyone sees it. - Confucius",
        "The journey of life is not about the destination but the lessons learned along the way. - Unknown",
        "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
        "You don’t drown by falling in the water; you drown by staying there. - Edwin Louis Cole",
        "The measure of intelligence is the ability to change. - Albert Einstein",
        "Be faithful in small things because it is in them that your strength lies. - Mother Teresa",
        "Our greatest glory is not in never falling, but in rising every time we fall. - Confucius",
        "A person who never made a mistake never tried anything new. - Albert Einstein",
        "The mind is everything. What you think you become. - Buddha",
        "Act only according to that maxim whereby you can, at the same time, will that it should become a universal law. - Immanuel Kant",
        "It is not what we get, but who we become, what we contribute, that gives meaning to our lives. - Tony Robbins",
        "Do not let making a living prevent you from making a life. - John Wooden",
        "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate. - Ralph Waldo Emerson",
        "Man cannot remake himself without suffering, for he is both the marble and the sculptor. - Alexis Carrel",
        "The greater the obstacle, the more glory in overcoming it. - Molière",
        "You can waste your lives drawing lines. Or you can live your life crossing them. - Shonda Rhimes",
        "A diamond is a chunk of coal that did well under pressure. - Henry Kissinger",
        "Success is not in what you have, but who you are. - Bo Bennett",
        "Life is not measured by the number of breaths we take, but by the moments that take our breath away. - Maya Angelou",
        "The function of education is to teach one to think intensively and to think critically. - Martin Luther King Jr.",
        "All our dreams can come true, if we have the courage to pursue them. - Walt Disney",
        "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
        "A journey of a thousand miles begins with a single step. - Lao Tzu",
        "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
        "Happiness depends upon ourselves. - Aristotle",
        "The mind is everything. What you think you become. - Buddha",
        "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
        "Dream big and dare to fail. - Norman Vaughan",
        "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
        "Don’t let yesterday take up too much of today. - Will Rogers",
        "Everything you’ve ever wanted is on the other side of fear. - George Addair",
        "In the middle of every difficulty lies opportunity. - Albert Einstein",
        "Fall seven times and stand up eight. - Japanese Proverb",
        "If opportunity doesn’t knock, build a door. - Milton Berle",
        "Do one thing every day that scares you. - Eleanor Roosevelt",
        "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
        "The best way out is always through. - Robert Frost",
        "Turn your wounds into wisdom. - Oprah Winfrey",
        "Action is the foundational key to all success. - Pablo Picasso",
        "Believe in yourself and all that you are. - Christian D. Larson",
        "It does not matter how slowly you go as long as you do not stop. - Confucius",
        "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
        "Do what you can, with what you have, where you are. - Theodore Roosevelt",
        "Courage is grace under pressure. - Ernest Hemingway",
        "Act boldly and unseen forces will come to your aid. - Dorothea Brande",
        "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
        "Go the extra mile, it’s never crowded. - Wayne Dyer",
        "Keep going. Everything you need will come to you at the perfect time. - Unknown",
        "A hero is no braver than an ordinary man, but he is brave five minutes longer. - Ralph Waldo Emerson",
        "Life isn’t about finding yourself. Life is about creating yourself. - George Bernard Shaw",
        "Our greatest weakness lies in giving up. - Thomas Edison",
        "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
        "Push yourself, because no one else is going to do it for you. - Unknown",
        "Doubt kills more dreams than failure ever will. - Suzy Kassem",
        "Act as though it is impossible to fail. - Dorothea Brande",
        "Work hard in silence, let your success be your noise. - Frank Ocean",
        "The secret of getting ahead is getting started. - Mark Twain",
        "Perseverance is not a long race; it is many short races one after another. - Walter Elliot",
        "Big jobs usually go to the men who prove their ability to outgrow small ones. - Ralph Waldo Emerson",
        "Do the hard things today and your future self will thank you. - Unknown",
        "A problem is a chance for you to do your best. - Duke Ellington",
        "Energy and persistence conquer all things. - Benjamin Franklin",
        "Your passion is waiting for your courage to catch up. - Isabelle Lafleche",
        "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
        "Act without expectation. - Lao Tzu",
        "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
        "Don’t wait. The time will never be just right. - Napoleon Hill",
        "If opportunity doesn’t knock, build a door. - Milton Berle",
        "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
        "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
        "Dream big and dare to fail. - Norman Vaughan",
        "Quality is not an act, it is a habit. - Aristotle",
        "It always seems impossible until it’s done. - Nelson Mandela",
        "Fall seven times and stand up eight. - Japanese Proverb",
        "Everything you’ve ever wanted is on the other side of fear. - George Addair",
        "What you do today can improve all your tomorrows. - Ralph Marston",
        "Well done is better than well said. - Benjamin Franklin",
        "Change your thoughts and you change your world. - Norman Vincent Peale",
        "Energy and persistence conquer all things. - Benjamin Franklin",
        "The best revenge is massive success. - Frank Sinatra",
        "You miss 100% of the shots you don’t take. - Wayne Gretzky",
        "Success doesn’t come to you, you go to it. - Marva Collins",
        "The secret of getting ahead is getting started. - Mark Twain",
        "We can do anything we want if we stick to it long enough. - Helen Keller",
        "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
        "Opportunities don’t happen. You create them. - Chris Grosser",
        "Turn your wounds into wisdom. - Oprah Winfrey",
        "You cannot swim for new horizons until you have courage to lose sight of the shore. - William Faulkner",
        "There are no shortcuts to any place worth going. - Beverly Sills",
        "Act boldly and unseen forces will come to your aid. - Dorothea Brande",
        "Courage is grace under pressure. - Ernest Hemingway",
        "Limit your 'always' and your 'nevers'. - Amy Poehler",
        "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
        "A journey of a thousand miles begins with a single step. - Lao Tzu",
        "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
        "In the middle of every difficulty lies opportunity. - Albert Einstein",
        "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
        "Doubt kills more dreams than failure ever will. - Suzy Kassem",
        "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
        "Small deeds done are better than great deeds planned. - Peter Marshall",
        "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
        "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
        "Hustle beats talent when talent doesn’t hustle. - Ross Simmonds",
        "Do one thing every day that scares you. - Eleanor Roosevelt",
        "Diligence is the mother of good luck. - Benjamin Franklin",
        "Work hard in silence, let your success be your noise. - Frank Ocean"
    )


    addQuotesToFirebase(quotesList3)
}